apiVersion: v1
kind: Service
metadata:
  name: menu-service
  labels:
    app: menu-dinner
spec:
  type: NodePort
  selector:
    app: menu-dinner
  ports:
    - name: http
      port: 8888          # Service port (inside cluster)
      targetPort: 8888    # Container port
      nodePort: 30080     # Exposed port on each node (must be 30000–32767)
